sudo: required
services:
  - docker
before_install:
  - openssl aes-256-cbc -K $encrypted_9f3b5599b056_key -iv $encrypted_9f3b5599b056_iv -in service-account.json.enc -out service-account.json -d
  - curl https://sdk.cloud.google.com > install_google_cloud_sdk.sh
  - /bin/bash install_google_cloud_sdk.sh --disable-prompts
  - source $HOME/google-cloud-sdk/path.bash.inc
  - gcloud components update kubectl --quiet
  - gcloud auth activate-service-account --key-file service-account.json
  - gcloud config set project eco-shift-326816
  - gcloud config set compute/zone us-central1-a
  - gcloud container clusters get-credentials multi-cluster
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USENAME" --password-stdin
  - docker build -t cpinochet/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run cpinochet/react-test npm test -- --coverage

deploy:
  provider: script
  script: bash ./deploy.sh
  on:
    branch: master
