sudo: required
services:
  - docker
before_install:
  - openssl aes-256-cbc -K $encrypted_9f3b5599b056_key -iv $encrypted_9f3b5599b056_iv -in service-account.json.enc -out service-account.json -d
  - curl https://sdk.cloud.google.com > install_google_cloud_sdk.sh
  - /bin/bash install_google_cloud_sdk.sh --disable-prompts
  - source $HOME/google-cloud-sdk/path.bash.inc
  - gcloud components update kubectl --quiet
  - gcloud auth activate-service-account --key-file service-account.json
  - gcloud config set project eco-shift-326816
  - gcloud config set compute/zone us-central1-a
  - gcloud container clusters list 
  - gcloud container clusters get-credentials multi-cluster
  - kubectl get nodes
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USENAME" --password-stdin
  - docker build -t cpinochet/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true cpinochet/react-test npm test

after_success:
  - echo "Travis_Job id is $TRAVIS_JOB_ID"
  - echo "Travis_commit is $TRAVIS_COMMIT"
  - STC=`echo ${TRAVIS_COMMIT::7}`
  - export $STC
  - echo $STC
  - echo "Travis_pull_requet_sha is $TRAVIS_PULL_REQUEST_SHA"
  - echo "Building Docker Images..."
  - docker build -t cpinochet/multi-client:${STC} -f ./client/Dockerfile ./client
  - docker build -t cpinochet/multi-server:${STC} -f ./server/Dockerfile ./server
  - docker build -t cpinochet/multi-worker:${STC} -f ./worker/Dockerfile ./worker
  - docker tag cpinochet/multi-client:${STC} cpinochet/multi-client:latest
  - docker push cpinochet/multi-client:${STC}
  - docker push cpinochet/multi-client:latest
  - docker tag cpinochet/multi-server:${STC} cpinochet/multi-server:latest
  - docker push cpinochet/multi-server:${STC}
  - docker push cpinochet/multi-server:latest
  - docker tag cpinochet/multi-worker:${STC} cpinochet/multi-worker:latest
  - docker push cpinochet/multi-worker:${STC}
  - docker push cpinochet/multi-worker:latest

deploy:
  provider: script
  script:
    - bash ./deploy.sh
  on:
    branch: master
