apiVersion: cert-manager.io/v1
 
kind: Certificate
metadata:
  name: yandilagata-ga-tls
spec:
  secretName: yandilagata-ga
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: yandilagata.ga
  dnsNames:
    - yandilagata.ga
    - www.yandilagata.ga