apiVersion: cert-manager.io/v1
 
kind: Certificate
metadata:
  name: jandilagata-tk-tls
spec:
  secretName: jandilagata-tk
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: jandilagata.tk
  dnsNames:
    - jandilagata.tk
    - www.jandilagata.tk